### ISSUE TITLE
[all push-API backends] consume the widened ArrayKind (Fp32/Fp64) and apply the fixlen-array `count` bound only inside the matching arm (§4.8)

### ISSUE THREAD

**Issue by Andste82** [sofa-buffers/generator#259]
The corelib half of Crucible finding **F-0042** is implemented and open as PRs in all seven affected repos. It is an **ABI change**, and generated code is its only consumer — so **sofabgen must land the matching backend change before those PRs can merge**. Until then, generated code fails to compile against them (measured below).

## Why the hook had to change

CORELIB_PLAN §4.8 fixes the decode order for a fixlen array: count (format ceiling only) → `fixlen_word` → §7.3 skip on a contradicting subtype **without** applying the schema `count` → schema bound only for a field that survives. Generated code could not implement it: the array-header hook fired before the `fixlen_word`, or carried `ArrayKind::Fixlen` — which says the array is a fixlen array, but not whether its elements are fp32 or fp64. An fp64 array arriving at a declared `fp32[N]` slot was therefore indistinguishable from the real thing.

## The pinned ABI

**`corelib-ts` already ships exactly this and is the reference implementation** — `src/constants.ts` plus `src/decode/{fast.ts,state.ts}`. The other seven now match it:

```
ArrayKind = { Unsigned = 0, Signed = 1, Fp32 = 2, Fp64 = 3 }
```

The `Fixlen` / `FIXLEN` / `.fixlen` member is **removed**. The hook fires **after** the `fixlen_word` on the fixlen path (integer arrays are unchanged — there is no second word). Two repos additionally gained a `kind` parameter they never had: `corelib-go` (`ArrayBegin(id, kind, count) error`) and `corelib-dart` (`onArrayBegin(id, kind, count)`).

| repo | PR | change |
|---|---|---|
| corelib-ts | — | reference, no change |
| corelib-rs | [#41](https://github.com/sofa-buffers/corelib-rs/pull/41) | enum only (call site already past the word) |
| corelib-zig | [#28](https://github.com/sofa-buffers/corelib-zig/pull/28) | enum only |
| corelib-cs | [#46](https://github.com/sofa-buffers/corelib-cs/pull/46) | enum + move the call past the word |
| corelib-java | [#54](https://github.com/sofa-buffers/corelib-java/pull/54) | enum + move |
| corelib-rs-no-std | [#61](https://github.com/sofa-buffers/corelib-rs-no-std/pull/61) | enum + move |
| corelib-dart | [#25](https://github.com/sofa-buffers/corelib-dart/pull/25) | **new `kind` param** + move |
| corelib-go | [#60](https://github.com/sofa-buffers/corelib-go/pull/60) | **new `kind` param** + move |

`corelib-c-cpp`, `corelib-cpp` and `corelib-py` need no change — their pull/descriptor APIs already deliver the field after both words, which MESSAGE_SPEC §7.3 explicitly blesses (*"an object-API profile that hands the schema to the corelib as a descriptor table and checks there is equally conformant"*). They are the differential control.

## What the backends must emit

Today, e.g. csharp:

```csharp
case (Root_arrays_nested, 0): if (kind != ArrayKind.Fixlen) break;
    if (count > 5) throw ...InvalidMessage;
    m.arrays.nested.fp32 = new float[count]; break;
```

An fp64 header at the fp32 slot passes `kind != Fixlen` and hits the bound. Required:

1. **split the single `Fixlen` arm into `Fp32` and `Fp64`**, listing each fixlen-array id only under the arm for its *declared* element subtype (`arrays.nested` id 0 under Fp32 only, id 1 under Fp64 only);
2. keep the `count > N` schema bound **inside** the matched arm, behind `if (kind != ArrayKind.Fp32) break;`, so a non-matching kind reaches the skip path;
3. keep arming the discard counter for the non-matching kind, and do **not** size or touch the declared field there;
4. **dart backend** — adopt the 3-arg `onArrayBegin` and emit the kind-keyed skip/fill/bound structure it currently lacks entirely;
5. **go backend** — adopt `ArrayBegin(id, kind, count) error` and make the id-keyed `if count > 5 { return sofab.ErrInvalidMsg }` conditional on the matching kind.

## Measured today, on the family branch `fix/F-0042-array-count-after-subtype`

Four backends fail to **compile** against the new corelibs, which is what makes this blocking rather than merely pending:

- **java** — `Probe.java:431,451,452: cannot find symbol: variable FIXLEN, location: class ArrayKind`
- **csharp** — `Message.cs(340,23),(362,23),(378,65),(379,65): CS0117: 'ArrayKind' does not contain a definition for 'Fixlen'`
- **zig** — `message.zig:400:14: enum 'types.ArrayKind' has no member named 'fixlen'`
- **dart** — `message.dart:201,297: onArrayBegin declared (int id, int count)`, override is now `(int id, ArrayKind kind, int count)`

rust / rust-no-std compile (the enum variant is only referenced where it is matched) but are still semantically unfixed until the arms split.

## Expected side effect — do not close #254 on it

Splitting the arm also stops java/csharp sizing a declared `float[]` from a skipped fp64 header (F-0042's row 1). **F-0039 / G-0023 stays separate**: its primary face is a non-fixlen `ARRAY_SIGNED` header at a `u8[]` slot, a different codegen path.

## Acceptance

Crucible's `wiretype_sweep` carries a **two-cell carve-out** for exactly this defect (`engine/structured/wiretype_sweep.py`, an fp array meeting a declared fp array of the other width). When this lands, delete the carve-out and the two cells must go green on their own — they are a bug, not a legal divergence.

Reproducers and the six-vector matrix: `findings/F-0042-fixlen-array-count-bound-precedes-subtype/` in the Crucible repo.

**Comment by Andste82** [comment]
Backend half is up as **#260** (draft) — all six push-API backends, with all seven corelib branches pinned in `.github/corelib-refs`.

Each declared fixlen array now sits under the arm for its own element subtype, with the `count > N` reject, the `max_dyn_array_count` reject and any sizing or clearing of the container **inside** that arm; a non-matching header falls through to the discard counter untouched. Two things beyond re-keying, both surfaced by a cross-backend review: **zig** also gated its count-less and nested-row arms (they allocated `count` slots from a header that was simultaneously being discarded), and **go**/**dart** now key their integer arms too, matching java/csharp/zig.

Testing worth calling out, because a green conformance run did **not** test this: no harness had a vector for an fp64 header at an fp32-declared slot. All six now carry the pair on `somefloatarray` (fp32, count 3, id 17) — `8d 01 05 41` + 5×8 zero bytes must **decode**, `8d 01 05 20` + 5×4 must stay **INVALID**. Mutation-tested: moving the bound back outside the kind test turns the first one red. Also a new `fp_array_subtypes.yaml` corpus definition, because no existing one declared both fp array subtypes, so the emitted form that *drops* the catch-all had no compiled coverage anywhere.

Two things this does **not** do:

1. **rust still keys its INTEGER arms kind-agnostically** — an fp header at a declared `u32[8]` still applies that field's bound and clears it, while the discard counter throws the elements away. That is the #254 / F-0039 face, and per this issue it stays separate. rust is now the last of the six carrying it; the emission site says so explicitly. Say the word and I'll align it in a follow-up.
2. **Crucible's `wiretype_sweep` carve-out** — the stated acceptance criterion. That repo is owned elsewhere, so deleting the two-cell carve-out and confirming the cells go green is a hand-off, not part of #260.

Unrelated but blocking: `lang-cpp` is red on `main` since corelib-cpp#59 / corelib-c-cpp#119 (F-0041) merged — our §5.2 ordering vector cut one byte before the fixlen word, where the over-index reject now correctly waits. Fixed separately in **#261** (green). Merge that first.

**Comment by Andste82** [comment]
Backend half is **merged**: #260 → `4c7a224`, with #261 (`91e5995`) ahead of it to clear an unrelated `lang-cpp` breakage.

All seven corelib PRs then merged too, so the ABI is closed on both sides:

| repo | PR | merge commit |
|---|---|---|
| corelib-rs | #41 | `b74de17` |
| corelib-rs-no-std | #61 | `380a9a9` |
| corelib-java | #54 | `79bf955` |
| corelib-cs | #46 | `d1fb48b` |
| corelib-zig | #28 | `995cd86` |
| corelib-dart | #25 | `812761b` |
| corelib-go | #60 | `4c6df2a` |

`.github/corelib-refs` is deleted again in #262 (`1543f83`). That turned out to matter more than housekeeping: the seven PRs merged with `--delete-branch`, so the pins pointed at branches that no longer existed, and `clone_corelib` fails hard on an unresolvable ref rather than falling back to `main` — every `lang-*` job on any future branch would have died at checkout. `main` hides that, because the composite action skips the pin file there.

**Two items keep this issue open:**

1. **Crucible's `wiretype_sweep` carve-out** — this issue's stated acceptance criterion. That repo is owned elsewhere, so deleting the two-cell carve-out and confirming the cells go green on their own is a hand-off. Everything it needs is now on `main` in all eight repos.
2. **rust's integer arms are still kind-agnostic** — an fp header at a declared `u32[8]` applies that field's bound and clears it, while the discard counter throws the elements away. That is the #254 / F-0039 face, deliberately out of scope here; rust is the last of the six carrying it and the emission site says so. Happy to align it on request.

**Comment by Andste82** [comment]
Closing: everything this issue asked of the generator is on `main`.

- **#260** (`4c7a224`) — all six push-API backends key each declared fixlen array to its own element subtype, with the schema `count` reject, the `max_dyn_array_count` reject and any sizing or clearing of the container inside that arm.
- **#261** (`91e5995`) — cleared an unrelated `lang-cpp` breakage that was blocking the above.
- All seven corelib PRs merged, so the ABI is closed on both sides.
- **#262** (`1543f83`) — `.github/corelib-refs` removed again.

Two things live on elsewhere, deliberately:

1. **Crucible's `wiretype_sweep` carve-out** — the acceptance criterion named here. That repo is owned elsewhere, so deleting the two cells and confirming they go green on their own is a hand-off; everything it needs is now on `main` in all eight repos. Reopen or file against Crucible if those cells do not come up green.
2. **rust's integer arms stay kind-agnostic** — tracked as #254 / Crucible F-0039, which this issue explicitly kept separate. rust is the last of the six carrying it, and the emission site says so.
